# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testschema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testschema.proto',
  package='iot1',
  serialized_pb='\n\x10testschema.proto\x12\x04iot1\"\xe3\x01\n\x10\x44\x65viceDataUpdate\x12\x35\n\ndefinition\x18\x01 \x03(\x0b\x32!.iot1.DeviceDataUpdate.Definition\x12+\n\x05\x65ntry\x18\x02 \x03(\x0b\x32\x1c.iot1.DeviceDataUpdate.Entry\x1a\x38\n\nDefinition\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x02(\t\x12\x0c\n\x04unit\x18\x03 \x02(\t\x1a\x31\n\x05\x45ntry\x12\r\n\x05\x64\x65\x66Id\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x12\n\n\x02ts\x18\x03 \x01(\t')




_DEVICEDATAUPDATE_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='iot1.DeviceDataUpdate.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='iot1.DeviceDataUpdate.Definition.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='category', full_name='iot1.DeviceDataUpdate.Definition.category', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='iot1.DeviceDataUpdate.Definition.unit', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=147,
  serialized_end=203,
)

_DEVICEDATAUPDATE_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='iot1.DeviceDataUpdate.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='defId', full_name='iot1.DeviceDataUpdate.Entry.defId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='iot1.DeviceDataUpdate.Entry.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='iot1.DeviceDataUpdate.Entry.ts', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=254,
)

_DEVICEDATAUPDATE = _descriptor.Descriptor(
  name='DeviceDataUpdate',
  full_name='iot1.DeviceDataUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='definition', full_name='iot1.DeviceDataUpdate.definition', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entry', full_name='iot1.DeviceDataUpdate.entry', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEDATAUPDATE_DEFINITION, _DEVICEDATAUPDATE_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=254,
)

_DEVICEDATAUPDATE_DEFINITION.containing_type = _DEVICEDATAUPDATE;
_DEVICEDATAUPDATE_ENTRY.containing_type = _DEVICEDATAUPDATE;
_DEVICEDATAUPDATE.fields_by_name['definition'].message_type = _DEVICEDATAUPDATE_DEFINITION
_DEVICEDATAUPDATE.fields_by_name['entry'].message_type = _DEVICEDATAUPDATE_ENTRY
DESCRIPTOR.message_types_by_name['DeviceDataUpdate'] = _DEVICEDATAUPDATE

class DeviceDataUpdate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Definition(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICEDATAUPDATE_DEFINITION

    # @@protoc_insertion_point(class_scope:iot1.DeviceDataUpdate.Definition)

  class Entry(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DEVICEDATAUPDATE_ENTRY

    # @@protoc_insertion_point(class_scope:iot1.DeviceDataUpdate.Entry)
  DESCRIPTOR = _DEVICEDATAUPDATE

  # @@protoc_insertion_point(class_scope:iot1.DeviceDataUpdate)


# @@protoc_insertion_point(module_scope)
